name: dirty_check
description: >
  Observe and be notified when a value changes.
version: 0.1.0
authors:
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/dirty_check

environment:
  sdk: ">=1.22.0 <2.0.0"

dependencies:
  async_track: ^0.2.0

dev_dependencies:
  test: ^0.12.20
